#include "SDCardLoggin.h"

// Global instance
SDCardLogger sdLogger;

bool SDCardLogger::init() {
    sdReady = false;
    lastFlushTime = 0;
    
    Serial.print("Initializing SD card...");
    
    // Initialize SD card using built-in SD slot on Teensy 4.1
    if (!SD.begin(SD_CHIP_SELECT)) {
        Serial.println(" FAILED!");
        Serial.println("SD card initialization failed. Check:");
        Serial.println("- SD card is inserted");
        Serial.println("- SD card is formatted (FAT32 recommended)");
        Serial.println("- SD card is not write-protected");
        return false;
    }
    
    Serial.println(" SUCCESS!");
    
    // Use fixed filename for single flight logging
    currentLogFileName = LOG_FILENAME;
    
    // Remove existing file to start fresh
    if (SD.exists(currentLogFileName.c_str())) {
        SD.remove(currentLogFileName.c_str());
        Serial.println("Cleared previous flight data");
    }
    
    // Open log file for writing
    logFile = SD.open(currentLogFileName.c_str(), FILE_WRITE);
    if (!logFile) {
        Serial.println("Failed to create log file: " + currentLogFileName);
        return false;
    }
    
    // Write CSV header
    if (!writeCSVHeader()) {
        Serial.println("Failed to write CSV header");
        logFile.close();
        return false;
    }
    
    sdReady = true;
    Serial.println("SD logging started: " + currentLogFileName);
    Serial.println("Free space: " + String(getFreeSpaceMB()) + " MB");
    
    return true;
}

bool SDCardLogger::logData(uint8_t throttle, uint8_t pitch, uint8_t yaw, uint8_t roll,
                          uint8_t killSwitch, bool emergencyStop, 
                          float batteryVoltage, float temperature) {
    return logDataWithCustomTime(millis(), throttle, pitch, yaw, roll, killSwitch, emergencyStop);
}

bool SDCardLogger::logDataWithCustomTime(unsigned long customTime, uint8_t throttle, uint8_t pitch, uint8_t yaw, uint8_t roll,
                                        uint8_t killSwitch, bool emergencyStop) {
    if (!sdReady || !logFile) {
        return false;
    }
    
    // Create CSV row: timestamp,throttle,pitch,yaw,roll,killswitch,emergency,battery,temp
    String logEntry = String(customTime) + "," +
                     String(throttle) + "," +
                     String(pitch) + "," +
                     String(yaw) + "," +
                     String(roll) + "," +
                     String(killSwitch) + "," +
                     (emergencyStop ? "1" : "0");
    
    // Write to file
    logFile.println(logEntry);
    
    // Auto-flush every 1 second for immediate data saving
    unsigned long currentTime = millis();
    if (currentTime - lastFlushTime >= 1000) {
        flush();
        lastFlushTime = currentTime;
    }
    
    return true;
}

bool SDCardLogger::logMessage(const String& message) {
    if (!sdReady || !logFile) {
        return false;
    }
    
    // Log message with timestamp in comment format
    String logEntry = getTimestamp() + ",,,,,,,, # " + message;
    logFile.println(logEntry);
    
    return true;
}

void SDCardLogger::flush() {
    if (logFile) {
        logFile.flush();
    }
}

void SDCardLogger::close() {
    if (logFile) {
        logFile.close();
        Serial.println("Log file closed: " + currentLogFileName);
    }
    sdReady = false;
}

String SDCardLogger::getCurrentLogFile() {
    return currentLogFileName;
}

bool SDCardLogger::isReady() {
    return sdReady;
}

uint32_t SDCardLogger::getFreeSpaceMB() {
    if (!sdReady) return 0;
    
    // Get volume info (this is a simplified approach)
    // For Teensy 4.1, we'll return a generic value as SD library doesn't provide direct access
    // In practice, you might implement a more sophisticated method
    return 1000; // Placeholder - return 1000MB
}



bool SDCardLogger::writeCSVHeader() {
    if (!logFile) return false;
    
    // Write CSV header with all columns
    String header = "Timestamp,Throttle,Pitch,Yaw,Roll,KillSwitch,Emergency";
    logFile.println(header);
    
    // Write metadata comments
    logFile.println("# Flight Data Log - Single Flight Mode");
    logFile.println("# Generated by Starship Hand Controller");
    logFile.println("# Timestamp: milliseconds since loop start (flight time)");
    logFile.println("# Control values: 0-255 (127=center)");
    logFile.println("# Emergency: 1=active, 0=normal");
    logFile.println("# File overwrites on each restart");
    logFile.println("# ========================");
    
    return true;
}

String SDCardLogger::getTimestamp() {
    // Return milliseconds since startup for system messages
    // Flight data uses custom timestamp from loop start
    return String(millis());
}